# Generated by Django 4.1.1 on 2023-01-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AptoProj',
            fields=[
                ('story_id', models.CharField(blank=True, max_length=4, primary_key=True, serialize=False)),
                ('data_apto', models.DateField(blank=True, max_length=255, null=True)),
                ('vlr_apto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apto_proj',
                'managed': True,
            },
        ),
    ]
